services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- --host
    environment:
      VITE_API_URL: http://postgrest:3000
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          initial_sync: true
          ignore:
            - dist/
            - node_modules/
        - action: sync+restart
          path: ./vite.config.js
          target: /app
        - action: rebuild
          path: ./frontend/package.json
  db:
    image: supabase/postgres:17.6.1.096
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      JWT_SECRET: reallyreallyreallyreallyverysafe
      JWT_EXP: 3600
    volumes:
      - data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8083:80
    depends_on:
      db:
        condition: service_healthy

  postgrest:
    image: postgrest/postgrest
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://authenticator:postgres@db:5432/postgres
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: reallyreallyreallyreallyverysafe
      PGRST_SERVER_HOST: 0.0.0.0
    ports:
      - 3000:3000
    command: ["postgrest"]
    depends_on:
      db:
        condition: service_healthy

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8084:8080"
    environment:
      API_URL: http://localhost:3000/

volumes:
  data: